### ISSUE TITLE
Stage component cause Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by rin-yato** [pmndrs/drei#1392]
``` js
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-reconciler.development.js:19378:11)
    at scheduleUpdateOnFiber (react-reconciler.development.js:17522:3)
    at dispatchSetState (react-reconciler.development.js:8564:16)
    at onCentered (Stage.js:102:7)
    at Center.js:40:7
    at commitHookEffectListMount (react-reconciler.development.js:14669:26)
    at commitLayoutEffectOnFiber (react-reconciler.development.js:14781:17)
    at commitLayoutMountEffects_complete (react-reconciler.development.js:16290:9)
    at commitLayoutEffects_begin (react-reconciler.development.js:16276:7)
    at commitLayoutEffects_begin (react-reconciler.development.js:16258:11)```

**Comment by tompelsama** [comment]
I got the same error.

**Comment by FrancescoChichi** [comment]
same error

**Comment by brunosimon** [comment]
Multiple students of Three.js Journey are reporting this too. Forcing the version to `9.50.3` exactly fixes it.

**Comment by FrancescoChichi** [comment]
same error with 9.50.3

**Comment by FrancescoChichi** [comment]
"@react-three/drei": "^9.50.3",
    "@react-three/fiber": "^8.12.0",

**Comment by tompelsama** [comment]
> ```
> "@react-three/drei": "^9.50.3",
> "@react-three/fiber": "^8.12.0",
> ```

If you run `npm install` it will install the latest minor version which is `9,64.0`. You should remove the caret to force the app to use that version. It should be like this `9.50.3`

**Comment by sszczep** [comment]
Same issue with:
```json
"react": "18.2.0",
"three": "^0.151.3",
"@react-three/fiber": "^8.12.0",
```

Works fine on `9.50.3`.

**Comment by drcmda** [comment]
should be fixed, in the version that's currently going through the CI

**Comment by fillybrese** [comment]
@drcmda should that merge also fix on React Native? Still getting it on drei/native v9.65.3 in RN v0.71.6.

**Comment by kavsingh** [comment]
Hi! am also still seeing this with

```json
    "@react-three/drei": "9.65.3",
    "@react-three/fiber": "8.12.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "three": "0.151.3"
```

Code sandbox repro here: https://codesandbox.io/s/drei-stage-callstack-uongqs?file=/src/App.tsx
Note: this happens with and without `React.StrictMode`

thanks!

**Comment by kavsingh** [comment]
seems to be fixed in `9.65.5` 🎉 
https://codesandbox.io/s/drei-stage-callstack-forked-6ulxb3?file=/package.json
thank you!!

**Comment by stphn** [comment]
Tested with: 
`"@react-three/drei": "^9.68.3",`

Seems to be fixed, that thread should can be closed
