### ISSUE TITLE
Multiple errors and warning

### ISSUE THREAD

**Issue by vinaysharma14** [pmndrs/drei#323]
- `three` version: ^0.126.1
- `react-three-fiber` version: ^5.0.0-beta.12
- `@react-three/drei` version: ^2.3.0-beta.1
- `node` version: 14.16.0
- `npm` (or `yarn`) version: 6.14.11

### Problem description:

1. **WARNING:** Multiple instances of Three.js being imported.
2. **TypeError:** element.setAttribute is not a function. (In 'element.setAttribute(eventName, 'return;')', 'element.setAttribute' is undefined)
3. **Invariant Violation:** "main" has not been registered. This can happen if: Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it, and restart it in the current project. A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
4. **Unable to resolve module** `use-asset` from /Users/username/Sites/projects/project-name/node_modules/@react-three/drei/index.cjs.js: use-asset could not be found within the project.

### Relevant code:

```js
import React, { useRef, useState, FC } from 'react';

import { Canvas, useFrame } from 'react-three-fiber';
import { OrbitControls } from '@react-three/drei';

interface Props {
  position: [number, number, number]
}

const Box: FC<Props> = ({ position }) => {
  // This reference will give us direct access to the mesh
  const mesh = useRef()

  // Set up state for the hovered and active state
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)

  // Rotate mesh every frame, this is outside of React without overhead
  useFrame(() => {
    mesh.current.rotation.x = mesh.current.rotation.y += 0.01
  })

  return (
    <mesh
      ref={mesh}
      position={position}
      scale={active ? [1.5, 1.5, 1.5] : [1, 1, 1]}
      onClick={() => setActive(!active)}
      onPointerOver={() => setHover(true)}
      onPointerOut={() => setHover(false)}
    >
      <boxBufferGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  )
}

export default () => (
  <Canvas>
    <ambientLight />
    <pointLight position={[10, 10, 10]} />
    <Box position={[-1.2, 0, 0]} />
    <Box position={[1.2, 0, 0]} />
    <OrbitControls />
  </Canvas>
);
```

### Suggested solution:

The last issue can be fixed by listing `use-asset` as a dependency in the packge.json

**Comment by joshuaellis** [comment]
You’re using a very outdated version of drei were I do believe we’ve already fixed this issue. If you can update your deps that’d be great, if you can continue to see errors we can revisit this issue.

**Comment by vinaysharma14** [comment]
@joshuaellis all the above-mentioned issues still persist with `^3.10.2` version of **@react-three/drei** as well, which I believe is the latest.

**Comment by joshuaellis** [comment]
Hm I can see this is to with `react-native`? It's normally pretty hard to solve without an example, are you able to share a repo of some sort? Either the original or a slimmed down version will do.

**Comment by vinaysharma14** [comment]
@joshuaellis yes, I'll share a minimal reproducible issue in a repo in 5 minutes.

**Comment by joshuaellis** [comment]
> 1. WARNING: Multiple instances of Three.js being imported.
> 2. TypeError: element.setAttribute is not a function. (In 'element.setAttribute(eventName, 'return;')', 'element.setAttribute' is undefined)
> 3. Invariant Violation: "main" has not been registered. This can happen if: Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it, and restart it in the current project. A module failed to load due to an error and AppRegistry.registerComponent wasn't called.
> 4. Unable to resolve module use-asset from /Users/username/Sites/projects/project-name/node_modules/@react-three/drei/index.cjs.js: use-asset could not be found within the project.


Okay, so I think there are potentially some issues with `drei` react-native support that unfortunately we don't have the maintainers with the skills & time to dedicate to the issue, so here's me fixing these errors loosely:

1. I'm not sure why this happens, it happens in codesandbox too, I think it's a problem with `three` not our library
2. & 3. First we have a `native` folder for imports that doesn't use `react-dom` although this doesn't solve the problem (as i said above, it's clearly not perfect) however, importing like so `@react-three/drei/core/OrbitControls` fixed these issues
4. I never saw this issue so it was probably a node_module issue.

**Comment by vinaysharma14** [comment]
@joshuaellis as suggested, importing **OrbitControls** from `@react-three/drei/core/OrbitControls` didn’t help either. Rather a new error throws up as below:

<img width="758" alt="Screenshot 2021-03-11 at 1 27 17 PM" src="https://user-images.githubusercontent.com/48080660/110754179-82a79900-826d-11eb-9068-8e05710bceae.png">

**Note:** Additionally Q2, Q3, and Q4 still exists.

**Comment by joshuaellis** [comment]
Have you installed the library `three-stdlib`? the fact it can't find it indicates you haven't and I imagine you're using the beta version of `@react-three/drei`.

**Comment by vinaysharma14** [comment]
@joshuaellis thanks for a quick response as always, but I'm not using the beta version of `@react-three/drei`. Moreover, despite installing `three-stdlib` explicitly, Q2, Q3, and Q4 still exist. It's pretty weird that none of these are reproducible for you. Anyway, thanks for your time.

**Comment by vinaysharma14** [comment]
@joshuaellis thanks for a quick response as always. Installing `three-stdlib` does solve the issue but I was wondering that usually developers don't install peer dependencies explicitly. I'm not using the beta version of `@react-three/drei` but `^3.10.2` as stated earlier.

Cleaning the cache of NPM and Expo did remove the Q2, Q3, Q4 errors but the canvas is not moving with finger gestures. Do the OrbitControls need any additional configuration?

![drei](https://user-images.githubusercontent.com/48080660/110770695-a378ea00-827f-11eb-98e2-f0a687e3db31.gif)

**Comment by joshuaellis** [comment]
> Installing three-stdlib does solve the issue but I was wondering that usually developers don't install peer dependencies explicitly.

this isn't true at all, take react, there are so many version of react, there are so many libraries that use react, I don't want to react bundled in every library I download – react-three-fiber, drei, react-dom – just to name three. Peer deps are 100% expected to be downloaded by the developers, you're thinking of actual dependencies such as `use-asset` where we have decided to specifically use a certain version and require that to be bundled. If you want peer deps to be installed by your manager, it sounds like an issue to take up with npm or yarn lol

> I'm not using the beta version of @react-three/drei but ^3.10.2 as stated earlier

I'm not sure why it wants you to install `three-stdlib` in that case then as we don't even use it on anything but the new v4 beta.

> the canvas is not moving with finger gestures. Do the OrbitControls need any additional configuration?

This will be an issue with `threejs`, we just port the implementation currently. I'm not sure why it won't work with `react-native` I haven't tried using three on rn, sorry.

**Comment by vinaysharma14** [comment]
@joshuaellis alright, thanks for your time and efforts! :)

**Comment by vinaysharma14** [comment]
@joshuaellis alright, thanks for your time and efforts! 🙂
