### ISSUE TITLE
Failed to parse source map 

### ISSUE THREAD

**Issue by Deepakmukka1** [pmndrs/drei#724]
- `three` version:0.136.0
- `@react-three/fiber` version: 7.0.24
- `@react-three/drei` version: 8.4.0
- `node` version: 14.17.3
- `npm` (or `yarn`) version: 7.19.1

### Problem description:

When i import  OrbitalControls from react-three/drie i get a warning Failed to parse source map from 'D:\\my-directory\node_modules\@chevrotain\utils\lib\src\api.js.map'

### Relevant code:

```js
import { OrbitControls } from '@react-three/drei'
```

### Screenshot of warning

The app works but the warning must be resolved to deploy

![image](https://user-images.githubusercontent.com/56472120/149657457-112b35cb-f289-4b90-8c17-3cceab41476b.png)

**Comment by CodyJasonBennett** [comment]
Seems to come from three-stdlib's VRMLLoader since it will import chevrotain from NPM. Maybe we should use three's vendored lib instead.

**Comment by CodyJasonBennett** [comment]
I believe I fixed this upstream at three-stdlib.

**Comment by ajnozari** [comment]
I'm still seeing this issue on 8.11.0.  Could they have changed something again?

**Comment by CodyJasonBennett** [comment]
Looks like I fixed similar for WebXR but for our own modules. This is an issue to bring up with https://github.com/Chevrotain/chevrotain.
